language: java

dist: trusty

# don't need more than a few levels for our builds
git:
  depth: 10
  quiet: true

cache:
  directories:
    - $HOME/.m2

before_install:
  - unset _JAVA_OPTIONS JRUBY_OPTS
  - rm ~/.m2/settings.xml
  - export MAVEN_SKIP_RC=true
  - export MAVEN_OPTS="-Xmn64M -Xmx512M -XX:CompressedClassSpaceSize=96M"
  - export JAVA_OPTS="$JAVA_OPTS -XX:CompressedClassSpaceSize=96M"
  - export JRUBY_OPTS="$WITH_JRUBY_OPTS"

before_script:
  - unset GEM_PATH GEM_HOME IRBRC
  - unset _JAVA_OPTIONS # travis/travis#8408
  - export PATH="`pwd`/bin:$PATH"
  - echo $HOME
  - echo $JAVA_OPTS
  - echo $JRUBY_OPTS
  - echo $MAVEN_OPTS

jdk:
  - openjdk8

os:
  - linux

env:
  global:
    - JAVA_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xms60M -Xmx720M -XX:InitialCodeCacheSize=40M -XX:ReservedCodeCacheSize=120M -Djava.security.egd=file:/dev/./urandom"
    - MALLOC_ARENA_MAX=2

install: true

matrix:
  fast_finish: true

  include:
    - stage: test
 
    - name: JRuby tests jit indy jdk11
      jdk: openjdk11
      script:
        - mvn clean package -Pbootstrap
        - bundle install
        - jruby -S rake test:jruby
      env: WITH_JRUBY_OPTS=-Xcompile.invokedynamic

    - name: JRuby tests jit indy jdk14
      jdk: openjdk14
      script:
        - mvn clean package -Pbootstrap
        - bundle install
        - jruby -S rake test:jruby
      env: WITH_JRUBY_OPTS=-Xcompile.invokedynamic

    - name: JRuby tests jit indy jdk16
      jdk: openjdk16
      script:
        - mvn clean package -Pbootstrap
        - bundle install
        - jruby -S rake test:jruby
      env: WITH_JRUBY_OPTS=-Xcompile.invokedynamic

    - name: JRuby tests jit indy
      script:
        - mvn clean package -Pbootstrap
        - bundle install
        - jruby -S rake test:jruby
      env: WITH_JRUBY_OPTS=-Xcompile.invokedynamic

  allow_failures:
    - env: PHASE='-Pjruby_complete_jar_extended -Dinvoker.skip=true'
    - name: concurrent ruby # temporary, see ruby-concurrency/concurrent-ruby#862

script: tool/maven-ci-script.sh

notifications:
  irc:
    on_success: change
    on_failure: always
    only:
      branch:
        - master
        - jruby-9.1
    template:
      - "%{repository_slug} (%{branch}:%{commit} by %{author}): %{message} %{build_url} [%{duration}]"
    channels:
      # - "irc.freenode.org#jruby"
      # note: `travis encrypt -r "jruby/jruby" "irc.freenode.org#jruby"`
      secure: "2DmwSfKvhnrdcC6LTXHHJ4QlSRXDlVUa9jEjXcdgIIZZm4ghbg/mmLjD6bv/ueCC8idQrYyuXRLeKIdaIss64q/lbbaj5VVV1p91fkZ3H+AhgHRPviboEm2bweSmjSWr7luXg4qifoL7YcXEtXw0YKGmub8WSZj4uPZbm5ce2l8="

services:
  - redis-server
  - haveged

addons:
  apt:
    packages:
      - haveged
